### ISSUE TITLE
Encoded Variables

### ISSUE THREAD

**Issue by tomitrescak** [katopz/react-apollo-graphql-github-example#2]
Hi, thanks for this app, it's a real inspiration.
I was wondering what these values represent and where they come from:

```
GITHUB_CLIENT_ID: 'e0b1671ff764de482212',
GITHUB_CLIENT_SECRET: '8f77dcfd6a807cff38ac558400c859f240806071'
```

**Comment by katopz** [comment]
Hi @tomitrescak sorry for late reply, refer to https://developer.github.com/v3/guides/basics-of-authentication/#accepting-user-authorization
```
Your client ID and client secret keys come from your application's configuration page. 
```
So go to this page
https://github.com/settings/developers

And create new app then get one :)

Cheers
